name: Release Preview

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  release_preview:
    uses: OpenVoiceOS/gh-automations/.github/workflows/release-preview.yml@05c0bb438ca7d2bc485465bc233fd4e1997f23c5
    with:
      package_name: 'ovos_ddg_plugin'
      version_file: 'ovos_ddg_plugin/version.py'
